services:
  api:
    build: .
    ports:
      - "3000:3000"

  banco:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: minha_api
    ports:
      - "5432:5432"